#!/bin/bash



# ------------
# Send an email.
# You can use it inside a loop. It sends only a mail,
# if the last mail is more than $timeDistance away.
#
# @author  Björn Hempel
# @version 1.0
# ------------
sendMailTimeFiltered ()
{
  local     sendMail="$1"
  local     timeFile="$2"
  local         text="$3"
  local      subject="$4"
  local    recipient="$5"
  local timeDistance=${6:-300}
  namespace="$recipient/"$(echo -ne "$text" | sha1sum | sed 's/ .*//')
     lastTimestamp=$(getLastTimeFromFile "$timeFile" "$namespace")
  currentTimestamp=$(getCurrentTimestamp)
  # the last email is not so long ago - stop here
  if [ "$(($currentTimestamp - $lastTimestamp))" -lt "$timeDistance" ]; then
    return 1
  fi
  # send email
  sudo -u service $pathScript/sendMail "$text" "$subject" "$recipient"
  # write new status
  setCurrentTimeToFile "$timeFile" "$namespace"
  # return success status
  return 0
}



