#!/bin/bash

# initial values
executionType="install"

# declare parameter list array
PARAMETERS=()

# read arguments
# help:
# help: Usage: %scriptname% [options...] {install|update|status}
while [[ $# > 0 ]]; do
    case "$1" in
        # help:  -h,    --help                    Shows this help.
        # help:
        -h|--help)
            cat "$BASH_SOURCE" | grep "# help:" | grep -v 'cat parameter' | sed 's/[ ]*# help:[ ]\?//g' | sed "s~%scriptname%~$scriptname~g"
            exit 0
            ;;

        # help:  -v,    --version                 Shows the version number.
        # help:
        -v|--version)
            [ "$(type -t showVersion)" == "function" ] && showVersion || echo "Create a showVersion function to show some text here."
            exit 0
            ;;

        #
        # collect all unknown parameters
        #
        *)
            PARAMETERS+=("$1")
            ;;
    esac
    shift
done

# assign mode to executionType var
if [ ! -z ${PARAMETERS[0]} ]; then
    executionType="${PARAMETERS[0]}"
fi

