#!/bin/bash

# ------------
# Tries to extract the complete virtual host block
# in given file $file on line $lineFrom. The function
# also replaces include commands with the content of
# the that include file. Relative include paths will
# be extended with given $serverRoot path.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-12)
# ------------
getVirtualHost()
{
    shopt -s nocasematch

    local        file="$1"
    local    lineFrom=$2
    local matchString='</VirtualHost>'
    local  serverRoot="$3"
    local  dockerName="$4"

    local content=$(getContentFromLineToMatch "$file" $lineFrom "$matchString" "$dockerName")
    local lastStatus=$?

    # no content found
    if [ $lastStatus -gt 0 ]; then
        echo -n "" && return $lastStatus
    fi

    # replace all "include paths"
    while [[ "$content" =~ (^|$'\n')([[:space:]]*)(include[[:space:]]+)([a-z0-9_/.-]+) ]]; do
        local fullstring="${BASH_REMATCH[3]}${BASH_REMATCH[4]}"
        local includePath="$serverRoot/${BASH_REMATCH[4]}"

        if [ "$dockerName" != "" ]; then
            local includeContent=$(docker exec -it $dockerName cat "$includePath")
        else
            local includeContent=$(cat "$includePath")
        fi

        content=$(echo "${content//$fullstring/$includeContent}")
    done

    echo "$content"
    return 0
}

# ------------
# Tries to extracts the target (document root, proxy target, redirect, etc)
# from given virtual config block in given $file on line $lineFrom.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-23)
# ------------
getTargetFromVirtualHostFile()
{
    shopt -s nocasematch

    local       file="$1"
    local   lineFrom=$2
    local serverRoot="$3"
    local dockerName="$4"

    local virtualHost=$(getVirtualHost "$file" $lineFrom "$serverRoot" "$dockerName")

    getTargetFromVirtualHost "$virtualHost"

    local lastStatus=$?

    return $lastStatus
}

# ------------
# Tries to extracts the target (document root, proxy target, redirect, etc)
# from the given virtual host block.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-23)
# ------------
getTargetFromVirtualHost()
{
    shopt -s nocasematch

    local virtualHost="$1"

    local documentRoot=$(echo "$virtualHost" | grep -i "DocumentRoot" | head -n 1)
    local proxyPass=$(echo "$virtualHost" | grep -i "ProxyPass[ $'\t']" | head -n 1)
    local rewriteRule=$(echo "$virtualHost" | grep -i "RewriteRule" | grep 301 | head -n 1)

    if [ "$documentRoot" != "" ]; then
        if [[ "$documentRoot" =~ ([\t ]*DocumentRoot[\t ]+)([a-z0-9/.-]+) ]]; then
            echo "file://${BASH_REMATCH[2]}"
            return 0
        else
            return 1
        fi
    fi

    if [ "$proxyPass" != "" ]; then
        if [[ "$proxyPass" =~ ([\t ]*ProxyPass[\t ]+[a-z0-9/.-]+[\t ]+)([a-z0-9/.:-]+) ]]; then
            echo "${BASH_REMATCH[2]}"
            return 0
        else
            return 1
        fi
    fi

    if [ "$rewriteRule" != "" ]; then
        local uri=$(echo "$rewriteRule" | awk '{print $3}')

        if [ "$uri" != "" ]; then
            echo "$uri"
            return 0
        else
            return 1
        fi
    fi

    return 1
}

# ------------
# Returns the server name from given virtual host.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-07-06)
# ------------
getServerNameFromVirtualHost()
{
    shopt -s nocasematch

    local virtualHost="$1"
    local servernameName="servername"

    local servername=$(echo "$virtualHost" | grep -i "servername")

    if [ "$servername" == "" ]; then
        return 1
    fi

    echo "$servername" | awk '{ print $2 }'
    return 0
}

# ------------
# Tries to get the server name from given project path.
# ATTENTION: This function needs root rights! Otherwise the required application apachectl won't be found.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-07-06)
# ------------
getServerNameFromProjectPath()
{
    local projectPath="$1"

    # check project path
    if [ ! -d "$projectPath" ]; then
        echo "The given project path \"$projectPath\" was not found."
        return 1
    fi

    local lines=$(apachectl -S | grep "namevhost")
    local serverRoot=$(apachectl -S | grep ServerRoot | awk '{print $2}' | sed -e 's/\"//g')

    # split lines from apachectl config output
    local lineArray=()
    while read -r line; do
        lineArray+=("$line")
    done <<< "$lines"

    # iterate through the returned virtual hosts configs from apachectl
    loopCounter=0
    for line in "${lineArray[@]}"; do
        local   port=$(echo "$line" | awk '{print $2}')
        local domain=$(echo "$line" | awk '{print $4}')
        local config=$(echo "$line" | awk '{print $5}')

        local     path=$(shopt -s nocasematch && [[ "$config" =~ \(([./a-z0-9\-]+) ]] && echo "${BASH_REMATCH[1]}")
        local lineFrom=$(shopt -s nocasematch && [[ "$config" =~ :([0-9]+)\) ]] && echo "${BASH_REMATCH[1]}")

        local virtualHost=$(getVirtualHost "$path" $lineFrom "/etc/apache2" "$DOCKER_NAME")
        local   targetUri=$(getTargetFromVirtualHost "$virtualHost")
        local  lastStatus=$?

        if [[ "$targetUri" =~ ^file://(.+) ]]; then
            targetUri="${BASH_REMATCH[1]}"
            if [[ "$targetUri" =~ ^$projectPath ]]; then
                servername=$(getServerNameFromVirtualHost "$virtualHost")
                lastStatus=$?

                echo -n "$servername"
                return 0
            fi
        fi
    done

    echo -n ""
    return 0
}

# ------------
# Tries to get the name from the project.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-05-29)
# ------------
getProjectNameFromVirtualHost()
{
    shopt -s nocasematch

    local virtualHost="$1"
    local nameName="name"

    local name=$(echo "$virtualHost" | grep "^#\([[:space:]]\)\+name:" | head -n1 | sed "s/^#[ ]\+name:[ ]\+//i")

    if [ "$name" == "" ]; then
        return 1
    fi

    echo "$name"
    return 0
}

