#!/bin/bash

# ------------
# Gets the certificate of given domain
#
# @author  Björn Hempel
# @version 1.0
# 
# ------------
getDomainCert()
{
    local domain="$1"

    openssl s_client -connect $domain:443 -servername $domain 2>&1 < /dev/null | \
        sed -n '/-----BEGIN/,/-----END/p'
}

# ------------
# Gets the issuer of given domain
#
# @author  Björn Hempel
# @version 1.0
# ------------
getIssuer()
{
    local domain="$1"

    openssl s_client -connect $domain:443 -servername $domain 2>&1 < /dev/null | \
        sed -n '/-----BEGIN/,/-----END/p' | \
        openssl x509 -noout -issuer | sed -r 's/^issuer= //'
}

# ------------
# Gets the chain certificate
#
# @author  Björn Hempel
# @version 1.0
# ------------
getChainCertificate()
{
    local domain="$1"

    local issuer=$(getIssuer "$domain")

    issuer=$(echo "$issuer" | sed 's/\//\\\//g')

    local chainCert=$(openssl s_client -connect $domain:443 -showcerts -servername $domain 2>/dev/null < /dev/null | sed -n "/s:$issuer/,/-----END/p" | sed -n '/-----BEGIN/,/-----END/p')

    echo "$chainCert"
}

# ------------
# Verifies the given certificate.
#
# @author  Björn Hempel
# @version 1.0
# ------------
isCertificateVerified()
{
    local certificateFile="$1"
    local chainFile="$2"
    local domain="$3"

    local status=$(openssl verify -CAfile "$chainFile" "$certificateFile" | grep ": OK")

    if [ "$status" != "" ]; then
        log 'passed' "The certificate from the domain \"$domain\" was successfully verified."
        return 0
    fi

    log 'failed' "The certificate from the domain \"$domain\" was not successfully verified."
    return 1
}

# ------------
# Checks the validity fo the given certificate.
#
# @author  Björn Hempel
# @version 1.0 (2017-03-11)
# ------------
isCertificateValid()
{
    local certificateFile="$1"
    local domain="$2"

    local warningDays=14

    # check certificate date
            currentTimestamp=$(getCurrentTimestamp)
         validUntilTimestamp=$(getValidUntilFromCertificate "$certificateFile" true)
        differenceValidUntil=$((validUntilTimestamp-currentTimestamp))
    differenceValidUntilDays=$((differenceValidUntil/60/60/24))

    validUntilFormated=$(date --date @$validUntilTimestamp +"%Y-%m-%d %H:%M")

    # certificate is valid more than $warningDays days
    if [ $differenceValidUntilDays -gt $warningDays ]; then
        log 'passed' "The certificate from the domain \"$domain\" is valid until \"$validUntilFormated\"."
        return 0
    fi

    # certificate is valid less then $warningDays days
    if [ $differenceValidUntilDays -gt 0 ]; then
        log 'warning' "The certificate from the domain \"$domain\" is only valid until \"$validUntilFormated\"."
        return 0;
    fi

    # certificate is expired.
    log 'failed' "The certificate from the domain \"$domain\" is not invalid. Expired at \"$validUntilFormated\"."
    return 1
}

# ------------
# Verifies the given chain certificate.
#
# @author  Björn Hempel
# @version 1.0
# ------------
isChainCertificateVerified()
{
    local chainFile="$1"
    local issuer="$2"

    local status=$(openssl verify "$chainFile" | grep ": OK")

    if [ "$status" != "" ]; then
        log 'passed' "The chainfile from the issuer \"$issuer\" was successfully verified."
        return 0;
    fi

    log 'failed' "The chainfile from the issuer \"$issuer\" was successfully verified."
    return 1
}

# ------------
# Gets the ocsp uri
#
# @author  Björn Hempel
# @version 1.0
# ------------
getOcspUri()
{
    local domain="$1"

    echo "$(getDomainCert $domain)" | openssl x509 -noout -ocsp_uri
}

# ------------
# Gets the ocsp uri
#
# @author  Björn Hempel
# @version 1.0
# ------------
isStatusOcspOk()
{
    local domain="$1"
    local chainfile="$2"
    local certFile="$3"
    local ocspUri=$(getOcspUri "$domain")
    local ocspHostname=$(getHostnameFromUrl $ocspUri)

    local status=$(openssl ocsp -issuer "$chainfile" -cert "$certFile" -url "$ocspUri" -CAfile "$chainfile" -verify_other "$chainfile" -header "HOST" "$ocspHostname" 2>&1)

    status=$(echo "$status" | grep "Response verify OK")

    if [ "$status" != "" ]; then
        log 'passed' "The ocsp is activated on domain \"$domain\" (\"$ocspUri\")."
        return 0
    fi

    log 'failed' "The ocsp is not activated on domain \"$domain\" (\"$ocspUri\")."
    return 1
}

# ------------
# Gets the valid until gmt date of the given certificate
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-03-11)
# ------------
getValidUntilFromCertificate()
{
    local certificateFile="$1"
    local timestamp=${2:-false}
  
    local validUntil=$(openssl x509 -noout -dates -in "$certificateFile" | \
        grep 'notAfter=' | \
        sed "s/.*notAfter=*//")

    if $timestamp; then
        validUntil=$(getTimestampFromDate "$validUntil")
    fi

    echo "$validUntil"
}

