#!/bin/bash


isPingableCheck()
{
    ip="$1"

    if isPingable "$ip"; then
        log 'passed' "The system with ip $ip is running"
        return 0
    else
        log 'failed' "The system with ip $ip is not pingable"
        return 1
    fi
}


isPortOpenCheck()
{
    ip="$1"
    port="$2"

    if isPortOpen "$ip" "$port"; then
        log 'passed' "The port \"$port\" on system with ip \"$ip\" is open."
        return 0
    else
        log 'failed' "The port \"$port\" on system with ip \"$ip\" is not open."
        return 1
    fi
}

isPortNotOpenCheck()
{
    if ! isPortOpen "$ip" "$port"; then
        log 'passed' "The port \"$port\" on system with ip \"$ip\" is closed."
        return 0
    else
        log 'failed' "The port \"$port\" on system with ip \"$ip\" is not closed."
        return 1
    fi
}

isHttpStatusCodeCheck()
{
    url="$1"
    expectedStatusCode="$2"

    if hasHttpStatusCodeFromUrl "$url" "$expectedStatusCode"; then
        log 'passed' "The url \"$url\" returns the expected status code \"$expectedStatusCode\""
        return 0
    else
        log 'failed' "The url \"$url\" does not return the expected status code \"$expectedStatusCode\""
        return 1
    fi
}

