#!/bin/bash

# ------------
# Gets the hostname from given url.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0
# @date    2017-03-05
# ------------
getHostnameFromUrl()
{
    local url="$1"

    echo "$url" | awk -F/ '{print $3}'
}

# ------------
# Builds a new url with given url, path and authentication.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0
# @date    2017-03-10
# ------------
buildUrl()
{
    local  url="$1"
    local path="${2:-}"
    local auth="${3:-}"

    protocol=$(getIndexFromStringSeparatedBySeparator "$url" "://" 0 2)

    if [ "$protocol" == "" ]; then
        protocol="http"
    fi

    # remove protocol
    url=$(getIndexFromStringSeparatedBySeparator "$url" "://" 1 2)

    # remove authentication
    if [ "$auth" != "" ]; then
        url=$(getIndexFromStringSeparatedBySeparator "$url" "@" 1 2)
        auth="$auth@"
    fi

    # TODO: remove path and add given path
 
    echo "${protocol}://${auth}${url}${path}"
}

# --------
# Builds the url and returns the ports with given url and config.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0
# @date    2017-03-11
# ------------
getUrlAndPorts()
{
       url="$1"
    config=$(echo "$2" | sed -e 's/:\/\//\[~doublepoint~\]\/\//g')

      auth=$(getIndexFromStringSeparatedBySeparator "$config" "@" 0 2)
    config=$(getIndexFromStringSeparatedBySeparator "$config" "@" 1 2)
     ports=$(getIndexFromStringSeparatedBySeparator "$config" ":" 0)
      path=$(getIndexFromStringSeparatedBySeparator "$config" ":" 1)
       url=$(buildUrl "$url" "$path" "$auth")

    # replace [~doublepoint~]// to ://
    ports=$(echo "$ports" | sed -e 's/\[~doublepoint~\]\/\//:\/\//g')   

    echo "$url" "$ports"
}

# --------
# Sort the given domain list and remove duplicates.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0 (2017-06-12)
# --------
sortDomainList()
{
    echo "$1" | sort -u | sed 's~\(http[s]*://\)~\1 ~' | sort -k2 | sed 's~:// ~://~'
}

