#!/bin/bash

# ------------
# Gets the hostname from given url.
#
# @author  Björn Hempel <bjoern@hempel.li>
# @version 1.0
# @date    2017-03-05
# ------------
getHostnameFromUrl()
{
    local url="$1"

    echo "$url" | awk -F/ '{print $3}'
}

