#!/bin/bash

# ------------
# Installs a git repository into a given folder
#
# @author  Björn Hempel
# @version 1.0 (2017-04-30)
# ------------
gitInstall ()
{
    local                projectGitUri="$1"
    local                  projectPath="$2"
    local       projectInstallQuestion=$(printf "$3" "$projectPath")
    local        projectInstallMessage=$(printf "$4" "$projectPath")
    local projectInstallSuccessMessage=$(printf "$5" "$projectPath")
    local   projectInstallErrorMessage=$(printf "$6" "$projectPath")
    local         projectCancelMessage="$7"

    # check global path folder
    if [ ! -d "$projectPath" ]; then
        # ask the user
        while true; do
            read -p "$projectInstallQuestion Type (y)es or (n)o: " -n 1 yn
            echo
            case $yn in
                [Yy]* )
                    log "info" "$projectInstallMessage"
                    result=$(git clone "$projectGitUri" "$projectPath" 2>&1);
                    break
                    ;;
                [Nn]* )
                    log "info" "$projectCancelMessage"
                    exit
                    ;;
                * )
                    echo "Please type (y)es or (n)o."
                    ;;
            esac
        done

        if [ $? -ne 0 ]; then
            log "error" "$projectInstallErrorMessage The git was executed with status $?."
            log "info"  "$result"
            return 1
        fi

        if [ ! -d "$projectPath" ]; then
            log "error" "$projectInstallErrorMessage The folder \"$project\" was not found."
            log "info"  "$result"
            return 1
        fi
    fi

    log "success" "$projectInstallSuccessMessage"

    return 0
}
