#!/bin/bash

# ------------
# Installs a git repository into a given folder
#
# @author  Björn Hempel
# @version 1.0 (2017-04-30)
# ------------
gitInstall ()
{
    local                projectGitZip="$1"
    local                  projectPath="$2"
    local                  projectName="$3"
    local                   branchName="$4"
    local       projectInstallQuestion=$(printf "$5" "$projectPath")
    local        projectInstallMessage=$(printf "$6" "$projectPath")
    local projectInstallSuccessMessage=$(printf "$7" "$projectPath")
    local   projectInstallErrorMessage=$(printf "$8" "$projectPath")
    local         projectCancelMessage="$9"

    # check global path folder
    if [ ! -d "$projectPath" ]; then
        # ask the user
        while true; do
            read -p "$projectInstallQuestion Type (y)es or (n)o: " -n 1 yn
            echo
            case $yn in
                [Yy]* )
                    log "info" "$projectInstallMessage"
                    result=$(wget -q "$projectGitZip" -O "/tmp/${projectName}.zip")
                    result=$(unzip -qq "/tmp/${projectName}.zip" -d /tmp)
                    result=$(mv "/tmp/${projectName}-${branchName}" "$projectPath")
                    result=$(rm "/tmp/${projectName}.zip")
                    break
                    ;;
                [Nn]* )
                    log "info" "$projectCancelMessage"
                    exit
                    ;;
                * )
                    echo "Please type (y)es or (n)o."
                    ;;
            esac
        done

        if [ $? -ne 0 ]; then
            log "error" "$projectInstallErrorMessage The git was executed with status $?."
            log "info"  "$result"
            return 1
        fi

        if [ ! -d "$projectPath" ]; then
            log "error" "$projectInstallErrorMessage The folder \"$project\" was not found."
            log "info"  "$result"
            return 1
        fi
    fi

    log "success" "$projectInstallSuccessMessage"

    return 0
}
