#!/bin/bash

# ------------
# Send an email.
# You can use it inside a loop. It sends only a mail,
# if the last mail is more than $timeDistance away.
#
# @author  Björn Hempel
# @version 1.0
# ------------
sendMailTimeFiltered ()
{
  local     sendMail="$1"
  local     timeFile="$2"
  local         text="$3"
  local      subject="$4"
  local    recipient="$5"
  local timeDistance=${6:-300}
  namespace="$recipient/"$(echo -ne "$text" | sha1sum | sed 's/ .*//')
     lastTimestamp=$(getLastTimeFromFile "$timeFile" "$namespace")
  currentTimestamp=$(getCurrentTimestamp)
  # the last email is not so long ago - stop here
  if [ "$(($currentTimestamp - $lastTimestamp))" -lt "$timeDistance" ]; then
    return 1
  fi
  # send email
  sudo -u service $pathScript/sendMail "$text" "$subject" "$recipient"
  # write new status
  setCurrentTimeToFile "$timeFile" "$namespace"
  # return success status
  return 0
}

# ------------
# Send error mails to given recipients. The first success mail will also be send.
#
# @author  Björn Hempel
# @version 1.0 (2017-04-19)
# ------------
sendErrorMailsTimeFiltered()
{
    local      subject="$1"
    local         text="$2"
    local   recipients="$3"
    local         from="$4"
    local      iniFile="$5"
    local    namespace="$6"
    local    errorMail=${7:-false}
    local timeDistance=${8:-300}

    IFS=',' read -r -a recipientArray <<< "$recipients"

    for recipient in "${recipientArray[@]}"; do
        local fullNamespace="${namespace}.error:${recipient}"

        local    lastErrorTimestamp=$(getCachedValue "$iniFile" "$fullNamespace" 0)
        local currentErrorTimestamp=$(getCurrentTimestamp)

        if $errorMail; then
            # the last email was send not so long ago
            if [ "$(($currentErrorTimestamp - $lastErrorTimestamp))" -lt "$timeDistance" ]; then
echo "ignore error mail to $recipient"
                continue;
            fi

            # send email
            echo -ne "$text" | mail -s "FAILED: $subject" -a "From: $from" "$recipient"
echo "send failed mail to $recipient"
            # set sent error time
            setCachedValue "$iniFile" "$fullNamespace" $currentErrorTimestamp
        else
            # no error mail was send before → no need to send this success mail
            if [ $lastErrorTimestamp -eq 0 ]; then
echo "ignore success mail to $recipient ($fullNamespace)"
                continue;
            fi

            # send email
            echo -ne "$text" | mail -s "SUCCESS: $subject" -a "From: $from" "$recipient"
echo "send success mail to $recipient ($fullNamespace)"
            # reset sent error time
            setCachedValue "$iniFile" "$fullNamespace" 0
        fi
    done
}

